(function(){'use strict';
if(window.__BASA_TRACK_CLOUD_SYNC__) return; window.__BASA_TRACK_CLOUD_SYNC__=true;
const IS_ONLINE=location.hostname.includes('github.io'); if(!IS_ONLINE) return;
const API='https://tpefvuspnvulalhwawqw.supabase.co/functions/v1/basa-track-api';
const APIKEY='sb_publishable_3eEsgRPTMMgONilc2ao-ag_FeT1TShW';
let cloudToken=sessionStorage.getItem('basa_cloud_token')||sessionStorage.getItem('basa_teacher_token')||localStorage.getItem('basa_teacher_token')||'',cloudRole=sessionStorage.getItem('basa_cloud_role')||localStorage.getItem('basa_teacher_role')||'',cloudLearnerId=sessionStorage.getItem('basa_cloud_learner')||'',teacherGateOpen=false;
if(cloudRole==='teacher'&&cloudToken){sessionStorage.setItem('basa_cloud_token',cloudToken);sessionStorage.setItem('basa_cloud_role','teacher');sessionStorage.setItem('basa_teacher_token',cloudToken);sessionStorage.setItem('basa_teacher_role','teacher');}
async function api(action,payload={}){const h={'Content-Type':'application/json','apikey':APIKEY};if(cloudToken)h.Authorization='Bearer '+cloudToken;const r=await fetch(API,{method:'POST',headers:h,body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
function localState(){try{return JSON.parse(localStorage.getItem('BASA_TRACK_COMBINED_V2')||'{}')}catch(e){return {}}}
function putLocalState(m){localStorage.setItem('BASA_TRACK_COMBINED_V2',JSON.stringify(m))}
function setRemoteState(id,s){const d=localState();d[id]=s;putLocalState(d)}
function safePct(done,total){const d=Number(done);const t=Number(total);if(!Number.isFinite(d)||!Number.isFinite(t)||t<=0)return 0;return Math.max(0,Math.min(100,Math.round((d/t)*100)))}
function safeTime(p,s){return p.lastLogin||p.last_login||p.last_login_at||p.lastAccess||p.last_access||s.lastLogin||s.last_login||s.last_login_at||'—'}
function clearTeacherSession(){sessionStorage.removeItem('basa_cloud_token');sessionStorage.removeItem('basa_cloud_role');sessionStorage.removeItem('basa_cloud_learner');sessionStorage.removeItem('basa_teacher_token');sessionStorage.removeItem('basa_teacher_role');localStorage.removeItem('basa_teacher_token');localStorage.removeItem('basa_teacher_role');cloudToken='';cloudRole='';cloudLearnerId='';}
async function cloudLogin(id,pin){const r=await api('login',{learner_id:id,pin});cloudToken=r.token;cloudRole=r.role;cloudLearnerId=r.learner_id||'';sessionStorage.setItem('basa_cloud_token',cloudToken);sessionStorage.setItem('basa_cloud_role',cloudRole);sessionStorage.setItem('basa_cloud_learner',cloudLearnerId);if(r.role==='teacher'){sessionStorage.setItem('basa_teacher_token',cloudToken);sessionStorage.setItem('basa_teacher_role','teacher');localStorage.setItem('basa_teacher_token',cloudToken);localStorage.setItem('basa_teacher_role','teacher');}if(r.role==='learner'&&cloudLearnerId){if(typeof DATA!=='undefined'){DATA.learners[cloudLearnerId]={name:r.display_name,pin};if(typeof saveRoster==='function')saveRoster()}if(r.state){const st={...(r.state||{}),lastLogin:r.state.lastLogin||r.state.last_login||new Date().toLocaleString()};setRemoteState(cloudLearnerId,st)}}return r}
async function syncLearnerState(id,state){if(!cloudToken||cloudRole!=='learner'||cloudLearnerId!==id)return;try{await api('save_progress',{state})}catch(e){console.warn('BASA cloud save:',e.message)}}
async function refreshLearner(id,render=true){if(!cloudToken||cloudLearnerId!==id)return;try{const r=await api('get_progress',{learner_id:id});if(r.progress){const c=localState()[id]||{};setRemoteState(id,{logins:c.logins||0,lastLogin:c.lastLogin||c.last_login||new Date().toLocaleString(),mar:r.progress.marungko||{},cl:r.progress.claveria||{},pg:r.progress.pagbasa||{}})}}catch(e){console.warn('BASA cloud load:',e.message)}if(render&&typeof origLearnerHome==='function')origLearnerHome()}
function hideTeacherEntry(){document.querySelectorAll('#home button').forEach(b=>{if(/Teacher Dashboard/i.test(b.textContent||''))b.style.display=cloudRole==='teacher'?'inline-block':'none'})}
function hideOnlineAdminTools(){['pupilManager','rosterEditor'].forEach(id=>{const e=document.getElementById(id);if(e)e.style.display='none'});const p=document.querySelector('#teacher .red');if(p&&/Reset Demo Progress/i.test(p.textContent||''))p.style.display='none';hideTeacherEntry()}
function showTeacherReturnButton(){if(cloudRole!=='teacher')return;let b=document.getElementById('basaTeacherReturn');if(!b){b=document.createElement('button');b.id='basaTeacherReturn';b.type='button';b.textContent='← Back to Teacher Dashboard';b.style.cssText='position:fixed;top:12px;left:12px;z-index:100000;background:#315c8c;color:#fff;border:0;border-radius:10px;padding:10px 14px;font:700 14px Arial,sans-serif;box-shadow:0 4px 14px rgba(0,0,0,.18);cursor:pointer';b.onclick=function(){try{if(typeof window.show==='function')window.show('teacher');setTimeout(refreshTeacher,250);}catch(e){console.warn('BASA return:',e)}};document.body.appendChild(b)}b.style.display='block'}
function hideTeacherReturnButton(){const b=document.getElementById('basaTeacherReturn');if(b)b.style.display='none'}
function teacherGate(){if(teacherGateOpen)return;teacherGateOpen=true;const old=document.getElementById('basaTeacherGate');if(old)old.remove();if(typeof origShow==='function')try{origShow('teacher')}catch(e){}const w=document.createElement('div');w.id='basaTeacherGate';w.style.cssText='position:fixed;inset:0;background:#0008;display:flex;align-items:center;justify-content:center;z-index:99999;padding:20px';w.innerHTML='<div style="background:#fff;border-radius:16px;max-width:420px;width:100%;padding:24px;box-shadow:0 16px 50px #0005"><h2 style="margin-top:0">👩‍🏫 Teacher Login</h2><p class="small">Online trial teacher account</p><input id="basaTeacherId" placeholder="Teacher ID" value="TEACHER-TEST" style="width:100%;box-sizing:border-box"><input id="basaTeacherPin" type="password" placeholder="PIN" style="width:100%;box-sizing:border-box"><div style="text-align:right;margin-top:8px"><button class="gray" id="basaTeacherCancel">Cancel</button><button class="green" id="basaTeacherGo">Log In</button></div><p id="basaTeacherMsg" class="small"></p></div>';document.body.appendChild(w);document.getElementById('basaTeacherCancel').onclick=()=>{w.remove();teacherGateOpen=false};document.getElementById('basaTeacherGo').onclick=async()=>{const m=document.getElementById('basaTeacherMsg');m.textContent='Checking…';try{const r=await cloudLogin(document.getElementById('basaTeacherId').value.trim(),document.getElementById('basaTeacherPin').value);if(r.role!=='teacher')throw new Error('Teacher account required');w.remove();teacherGateOpen=false;window.show('teacher')}catch(e){m.textContent='Maling Teacher ID o PIN.'}}}
const origShow=window.show,origLogin=window.login,origSave=window.save,origLearnerHome=window.learnerHome,origTeacher=window.teacher,origLogout=window.logout;
if(typeof origShow==='function')window.show=function(id){if(id==='teacher'&&cloudRole!=='teacher'){teacherGate();return}const r=origShow.apply(this,arguments);if(id==='teacher'){hideOnlineAdminTools();hideTeacherReturnButton();setTimeout(refreshTeacher,150)}else{hideTeacherEntry();if(cloudRole==='teacher')showTeacherReturnButton()}return r};
if(typeof origLogin==='function')window.login=async function(){const id=document.getElementById('lid').value.trim().toUpperCase(),pin=document.getElementById('pin').value;try{await cloudLogin(id,pin);origLogin()}catch(e){document.getElementById('msg').textContent='Maling Learner ID o PIN o hindi available online.'}};
if(typeof origSave==='function')window.save=function(d){const r=origSave.apply(this,arguments),id=cloudLearnerId;if(cloudToken&&cloudRole==='learner'&&id&&d&&d[id])syncLearnerState(id,d[id]);return r};
if(typeof origLearnerHome==='function')window.learnerHome=function(){if(cloudRole==='learner'&&cloudLearnerId){refreshLearner(cloudLearnerId,true);return}const r=origLearnerHome.apply(this,arguments);if(cloudRole==='teacher')showTeacherReturnButton();return r};
function renderCloudTeacher(pupils){
  const rows=[];
  (pupils||[]).forEach(p=>{
    const s=p.state||{},mar=s.mar||{},cl=s.cl||{},pg=s.pg||{};
    const marPct=safePct(Array.isArray(mar.done)?mar.done.length:0,26);
    const clTotal=(typeof DATA!=='undefined'&&DATA.claveria&&Array.isArray(DATA.claveria.checkpoints))?DATA.claveria.checkpoints.length:0;
    const pgTotal=(typeof DATA!=='undefined'&&DATA.pagbasa&&Array.isArray(DATA.pagbasa.checkpoints))?DATA.pagbasa.checkpoints.length:0;
    const clPct=safePct(cl.validated,clTotal);
    const pgPct=safePct(pg.validated,pgTotal);
    let approval='No pending approval';
    if(mar.pending&&!mar.approved) approval='<button class="green" onclick="apMar(\''+p.learner_id+'\')">Approve Marungko CP '+((Number(mar.validated)||0)+1)+'</button>';
    else if(cl.pending) approval='<button class="green" onclick="apCl(\''+p.learner_id+'\')">Approve Claveria CP '+(Number(cl.cp)||1)+'</button>';
    else if(pg.pending) approval='<button class="green" onclick="apPg(\''+p.learner_id+'\')">Approve Pagbasa CP '+(Number(pg.cp)||1)+'</button>';
    rows.push('<tr><td><b>'+String(p.display_name||p.name||'Pupil')+'</b><br>'+String(p.learner_id||'')+'</td><td>'+safeTime(p,s)+'</td><td>Marungko '+marPct+'%<br>Claveria '+clPct+'%<br>Pagbasa '+pgPct+'%</td><td>'+approval+'</td></tr>');
  });
  const dash=document.getElementById('dash');
  if(dash)dash.innerHTML='<table><tr><th>Learner</th><th>Last Access</th><th>Progress</th><th>Teacher Validation</th></tr>'+rows.join('')+'</table>';
}
async function refreshTeacher(){if(cloudRole!=='teacher')return;try{const r=await api('list_pupils');const d=localState();if(typeof DATA!=='undefined'){DATA.learners={};(r.pupils||[]).forEach(p=>{DATA.learners[p.learner_id]={name:p.display_name,pin:'0000'};d[p.learner_id]=p.state||d[p.learner_id]||{}});if(typeof saveRoster==='function')saveRoster()}(r.pupils||[]).forEach(p=>{const old=d[p.learner_id]||{};const incoming=p.state||{};d[p.learner_id]={...old,...incoming,lastLogin:safeTime(p,{...old,...incoming})}});putLocalState(d);renderCloudTeacher(r.pupils||[]);hideOnlineAdminTools()}catch(e){console.warn('BASA teacher refresh:',e.message);const msg=String(e&&e.message||'');if(/teacher session required|invalid token|unauthorized|jwt/i.test(msg)){clearTeacherSession();hideTeacherReturnButton();teacherGate();return}const dash=document.getElementById('dash');if(dash)dash.innerHTML='<div class="status">Cloud error: '+e.message+'</div>';}}
if(typeof origTeacher==='function')window.teacher=function(){const r=origTeacher.apply(this,arguments);if(cloudRole==='teacher'){hideOnlineAdminTools();hideTeacherReturnButton();setTimeout(refreshTeacher,250)}return r};
['apMar','apCl','apPg','resetPupilProgress'].forEach(fn=>{const orig=window[fn];if(typeof orig==='function')window[fn]=function(id){const r=orig.apply(this,arguments);if(cloudRole==='teacher'&&id)setTimeout(async()=>{try{const d=localState();await api('update_progress',{learner_id:id,state:d[id]||{}});await refreshTeacher()}catch(e){console.warn('BASA teacher save:',e.message)}},120);return r}});
const origOpen=window.openPupilAccount;if(typeof origOpen==='function')window.openPupilAccount=async function(id){if(cloudRole==='teacher'){try{const r=await api('get_progress',{learner_id:id});if(r.progress){const d=localState();d[id]={...(d[id]||{}),mar:r.progress.marungko||{},cl:r.progress.claveria||{},pg:r.progress.pagbasa||{}};putLocalState(d)}}catch(e){console.warn('BASA open pupil:',e.message)}}const r=origOpen.apply(this,arguments);if(cloudRole==='teacher')setTimeout(showTeacherReturnButton,200);return r};
if(typeof origLogout==='function')window.logout=function(){clearTeacherSession();hideTeacherEntry();hideTeacherReturnButton();return origLogout.apply(this,arguments)};
window.basaCloudRefreshTeacher=refreshTeacher;window.basaCloudTeacherGate=teacherGate;setTimeout(hideTeacherEntry,300);
})();